create database bd_maromba;
use bd_maromba;

create table Produtos(
    id int unsigned primary key not null auto_increment,
    nome varchar(200) not null,
    descricao longtext not null,
    preco decimal(9,2) not null,
    quantidade int not null,
    categoria varchar(100) not null,
    imagem varchar(3000) not null
);

create table Clientes(
    id int unsigned primary key not null auto_increment,
    nome varchar(30) not null,
    sobrenome varchar(30) not null,
    endereco varchar(60),
    telefone varchar(20),
    RG varchar(20),
    CPF varchar(20),
    email varchar(50),
    genero enum('m','f') not null,
    birthdate date
);

create table Pedidos(
numero int unsigned primary key not null auto_increment,
pcodigo int unsigned,
dtElaboracao date not null,
foreign key (numero) references Clientes(id),
foreign key (pcodigo) references Produtos(id)
);


create table Comentarios(
    numero int unsigned primary key not null auto_increment,
    idCliente int unsigned not null,
    pcodigo int unsigned not null,
    texto mediumtext not null,
    foreign key (idCliente) references Clientes(id),
    foreign key (pcodigo) references Produtos(id)
);

-- LUCAS
INSERT INTO `produtos` (`id`, `nome`, `descricao`, `preco`, `quantidade`, `categoria`, `imagem`) VALUES
(1, '(TOP) WHEY PROTEIN CONCENTRADO (1KG) - GROWTH SUPP', 'Whey Protein Growth é a proteína ideal para quem treina hipertrofia e quer ganhar massa muscular.\r\n\r\nIdeal porque é um suplemento de alto valor biológico, com grande concentração de proteínas e aminoácidos e também rico em Glutamina, BCAA e Leucina.', '76.50', 1, 'Vegetarianos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/185/01-desk.png'),
(2, '(TOP) WHEY PROTEIN ISOLADO (1KG) - GROWTH SUPPLEME', 'O produto na forma isolada varia entre uma concentração proteica de 90% (no caso do produto da Growth Supplements) a 95%. Em sua composição existe uma quantidade baixa (ou nenhuma) de carboidratos e um valor praticamente inexistente de gordura.\r\n\r\nO whey protein isolado surte um melhor efeito naquelas pessoas que já possuem uma rotina de treinos intensos e que possuem uma certa restrição de carboidratos na dieta.', '139.50', 1, 'Vegetarianos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/196/produto.png'),
(3, 'CREATINA (250G) (CREAPURE®) - GROWTH SUPPLEMENTS', 'A creatina é um derivado de aminoácidos obtida através da dieta de síntese por nosso próprio organismo. Ela está presente essencialmente no músculo e auxilia na manutenção dos níveis de energia durante períodos breves de exercício intenso. Ou seja, sua função é crucial nos treinos com muito peso na busca pelo ganho de massa.', '41.40', 1, 'Vegetarianos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/70/produto.png'),
(4, 'BCAA (10:1:1) (200G) (EM PÓ) - GROWTH SUPPLEMENTS ', 'Um dos suplementos líderes em vendas, o BCAA é a opção perfeita para quem deseja ter mais energia no treino e garantir o ganho de massa muscular. O produto da Growth oferece uma concentração ainda melhor para quem está focado na hipertrofia.\r\n\r\nA combinação de aminoácidos tem uma proporção que privilegia o nutriente mais anabólico, a Leucina. Ou seja, é um BCAA com resultados ainda melhores para quem busca se desafiar cada vez mais.', '100.80', 2, 'Vegetarianos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/13/produto.png'),
(5, 'BCAA (2:1:1) (200G) (EM PÓ) - GROWTH SUPPLEMENTS', 'Não saia perdendo na busca pelo resultado no seu treino. Afinal, a nutrição é fundamental para garantir que a tão sonhada hipertrofia esteja presente em sua rotina. Prático e com todos os nutrientes que você precisa para ganhar e manter a massa muscular, o BCAA em pó da Growth Supplements é a escolha perfeita.\r\n\r\nNa hora de investir nos melhores suplementos, não tenha dúvida: qualidade em primeiro lugar. Os produtos Growth são aprovados em testes internos e também em laboratórios parceiros, seguindo os critérios mais rigorosos da Anvisa. Assim, seu investimento vale a pena e os resultados chegam ainda mais rápido à sua rotina. Pronto para incluir agora o BCAA em pó no seu dia a dia?\r\n\r\n', '84.60', 2, 'Vegetarianos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/17/product.png'),
(6, 'BCAA (5:1:1) (200G) (EM PÓ) - GROWTH SUPPLEMENTS', 'Aproveite as melhores opções de BCAA na hora de focar no seu treino e na dieta. Esse suplemento oferece excelentes concentrações de Leucina, Valina e Isoleucina. Esses três componentes são os famosos aminoácidos de cadeia ramificada, conhecidos também entre os aminoácidos essenciais.\r\n\r\nEles precisam ser ingeridos por meio da dieta, justamente porque nosso corpo não tem a capacidade de produzi-los por conta própria. Isso torna esse produto excelente para quem está buscando o ganho de massa muscular e o emagrecimento. Isso porque eles compõem um terço de todo o tecido muscular do nosso organismo. Pronto para sentir todos os benefícios?', '101.80', 2, 'Vegetarianos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/22/product.png'),
(7, 'CREATINA MONOHIDRATADA 100GR - GROWTH SUPPLEMENTS', 'Sua lista de suplementos não está completa sem a Creatina Monohidratada da Growth Supplements.Esse produto é uma das principais escolhas dos atletas mais famosos e de quem está investindo na hipertrofia.Você consegue ganhar massa muscular e, ao mesmo tempo, garantir um ganho de força sem igual. Tudo isso seguido de resultados cada vez melhores nos treinos e da evolução que você buscava na sua atividade física de alta intensidade.\r\nNão tem como ignorar todos esses benefícios da creatina, venha aproveitar o suplemento Growth!', '18.00', 1, 'Vegetarianos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/71/product.png'),
(8, 'WHEY PROTEIN HIDROLISADO (1KG) (SABOR NATURAL) - G', 'Um dos suplementos mais avançados em nutrição esportiva e até mesmo no tratamento médico, o Whey Protein Hidrolisado é um dos campeões de venda da Growth Supplements.\r\n\r\nTrata-se de um suplemento de alta concentração de proteínas que usa o soro do leite como matéria-prima. Os efeitos são sentidos diretamente no desempenho e nos resultados dos treinos. Com o Whey Hidrolisado, você tem acesso à proteína hidrolisada, pré-digerida. Dessa forma, seu corpo absorve esse nutriente com muito mais rapidez, agindo diretamente na reconstrução do tecido muscular depois do treino.\r\n\r\n', '153.00', 1, 'Vegetarianos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/195/product.png'),
(9, 'PROTEÍNA DA ERVILHA - (1KG) (COM SABOR) - GROWTH S', 'Engana-se quem pensa que somente é possível ingerir a quantidade ideal de proteínas para uma dieta por meio de suplementos de origem animal. A proteína da ervilha, ou Pea Protein, é um suplemento proteico de alto valor biológico e com nutrientes que garantem tudo aquilo que é preciso para potencializar os resultados de um treino bem intenso.\r\n\r\nA produção do Pea Protein tem a ervilha como base, ou seja, uma opção perfeita para veganos. Além da ervilha, são acrescentados diversos aminoácidos essenciais, ideais para quem tem a hipertrofia como objetivo principal.', '67.50', 1, 'Vegetarianos', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_prote-na-da-ervilha-1kg-growth-supplements.jpg'),
(10, '(TOP) WHEY E EGG (SABOR NATURAL) (1KG) - GROWTH SU', 'Quem está em busca de uma vida mais saudável e tem a hipertrofia como objetivo principal precisa conhecer mais sobre o Whey e Egg da Growth Supplements. Esse produto é um suplemento proteico à base de whey protein com albumina. Saiba mais sobre ele e entenda o motivo de acrescentá-lo em sua dieta.', '72.00', 1, 'Vegetarianos', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_top-whey-e-egg-sabor-natural-1kg-growth-supplements.jpg'),
(11, 'WAXY MAIZE (1KG) - GROWTH SUPPLEMENTS', 'Quem pensa em aumentar a capacidade de treino e garantir ainda mais energia deve apostar no Waxy Maize. O produto foi desenvolvido pensando nas necessidades de praticantes de atividade física de alta intensidade, justamente porque ele fornece o combustível necessário para superar os limites e garantir resultados melhores. Trata-se de um produto feito à base de carboidratos complexos de alta qualidade, voltado especialmente para os atletas.', '21.60', 1, 'Vegetarianos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/179/product.png'),
(12, 'SOY PROTEIN (PROTEÍNA ISOLADA DE SOJA) 1KG - GROWT', 'A proteína de soja (Soy Protein) da Growth Supplements é um suplemento proteico perfeito para os vegetarianos que têm a hipertrofia como objetivo ou que apenas querem manter uma boa quantidade de proteínas no organismo para um cotidiano mais saudável.\r\nCom um altíssimo valor biológico, a proteína de soja oferece a quantidade ideal de nutrientes e proteínas para você enfrentar as suas atividades do dia a dia e também os treinos mais intensos. Inclusive, diferentemente do Whey, o Soy Protein pode ser consumido por pessoas intolerantes à lactose.\r\n\r\n', '39.60', 1, 'Vegetarianos', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_soy-protein-prote-na-isolada-de-soja-1kg-growth-supplements.jpg'),
(13, 'CREATINA (250G) (CREAPURE®) - GROWTH SUPPLEMENTS', 'A Growth Supplements garante os melhores preços aliados à alta qualidade. A vantagem é encontrar uma fabricante brasileira que venda direto para o consumidor. Assim, você aproveita a alta tecnologia aplicada ao processo de fabricação com a facilidade de receber o produto direto na sua casa. A Creapure® é uma fabricante campeã de vendas, produzindo a matéria-prima utilizada pelas principais marcas importadas. Assim, fica mais fácil consumir um material conceituado a um preço acessível que cabe no seu bolso, como é o caso da creatina.', '82.80', 1, 'Vegano', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/70/produto.png'),
(14, 'L-GLUTAMINA (250G) - GROWTH SUPPLEMENTS', 'Indispensável para o metabolismo de um corpo saudável, a glutamina tem importantes funções tanto para quem pratica exercícios físicos intensos quanto para quem busca apenas uma rotina ainda mais saudável.\r\n\r\nUm dos mais procurados, graças à altíssima qualidade e a resultados inevitáveis, é o whey isolado. Para saber mais sobre ele, continue a leitura.\r\n\r\nO suplemento glutamina ou L-glutamina da Growth Supplements traz a qualidade da marca e a segurança de anos de pesquisa. Ela é estudada há mais de 50 anos pela ciência, e a lista dos seus benefícios para o organismo só aumenta. A Growth recomenda também que ela seja consumida junto com uma fonte de proteína de alto valor biológico: isso garante que ela desempenhe todo seu potencial e apresente os melhores resultados.\r\n\r\nQuando consumida isoladamente, a glutamina acaba sendo absorvida pelas células do sistema gastrointestinal, não apresentando os benefícios de maneira completa.', '43.20', 1, 'Vegano', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/85/produto.png'),
(15, 'BCAA (10:1:1) (200G) (EM PÓ) - GROWTH SUPPLEMENTS', 'Um dos suplementos líderes em vendas, o BCAA é a opção perfeita para quem deseja ter mais energia no treino e garantir o ganho de massa muscular. O produto da Growth oferece uma concentração ainda melhor para quem está focado na hipertrofia.\r\n\r\nA combinação de aminoácidos tem uma proporção que privilegia o nutriente mais anabólico, a Leucina. Ou seja, é um BCAA com resultados ainda melhores para quem busca se desafiar cada vez mais.', '50.40', 1, 'Vegano', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/13/produto.png'),
(16, 'BCAA (2:1:1) (200G) (EM PÓ) - GROWTH SUPPLEMENTS', 'Não saia perdendo na busca pelo resultado no seu treino. Afinal, a nutrição é fundamental para garantir que a tão sonhada hipertrofia esteja presente em sua rotina. Prático e com todos os nutrientes que você precisa para ganhar e manter a massa muscular, o BCAA em pó da Growth Supplements é a escolha perfeita.\r\n\r\nNa hora de investir nos melhores suplementos, não tenha dúvida: qualidade em primeiro lugar. Os produtos Growth são aprovados em testes internos e também em laboratórios parceiros, seguindo os critérios mais rigorosos da Anvisa. Assim, seu investimento vale a pena e os resultados chegam ainda mais rápido à sua rotina. Pronto para incluir agora o BCAA em pó no seu dia a dia?', '42.30', 1, 'Vegano', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/17/product.png'),
(17, 'BCAA (5:1:1) (200G) (EM PÓ) - GROWTH SUPPLEMENTS', 'Aproveite as melhores opções de BCAA na hora de focar no seu treino e na dieta. Esse suplemento oferece excelentes concentrações de Leucina, Valina e Isoleucina. Esses três componentes são os famosos aminoácidos de cadeia ramificada, conhecidos também entre os aminoácidos essenciais.\r\n\r\nEles precisam ser ingeridos por meio da dieta, justamente porque nosso corpo não tem a capacidade de produzi-los por conta própria. Isso torna esse produto excelente para quem está buscando o ganho de massa muscular e o emagrecimento. Isso porque eles compõem um terço de todo o tecido muscular do nosso organismo. Pronto para sentir todos os benefícios?', '45.90', 1, 'Vegano', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/22/product.png'),
(18, 'CREATINA MONOHIDRATADA 100GR - GROWTH SUPPLEMENT', 'Sua lista de suplementos não está completa sem a Creatina Monohidratada da Growth Supplements.Esse produto é uma das principais escolhas dos atletas mais famosos e de quem está investindo na hipertrofia.Você consegue ganhar massa muscular e, ao mesmo tempo, garantir um ganho de força sem igual. Tudo isso seguido de resultados cada vez melhores nos treinos e da evolução que você buscava na sua atividade física de alta intensidade.\r\nNão tem como ignorar todos esses benefícios da creatina, venha aproveitar o suplemento Growth!', '54.00', 3, 'Vegano', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/71/product.png'),
(19, 'PALATINOSE 1KG - GROWTH SUPPLEMENTS', 'Para quem não conhece, a Palatinose — ou Isomaltulose — é um tipo de carboidrato muito específico na natureza e que se difere de todos os outros que têm por aí. Isso porque a Palatinose é o único carboidrato que existe no planeta que é totalmente digerido pelo organismo humano.\r\n\r\nIsso faz com que ela seja muito mais eficaz e poderosa que a famosa batata-doce, por exemplo. É um carboidrato mega saudável, que é facilmente e completamente digerido e vai ajudar você a ter um corpo forte, em forma e bem saudável.\r\n\r\nMas de onde vem esse incrível nutriente? A Palatinose é um derivado de carboidratos proveniente da beterraba, que também pode ser encontrado no mel e na cana de açúcar. Ela é obtida por meio de um processo de aplicação de enzimas nesses vegetais.', '76.50', 1, 'Vegano', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_palatinose-1kg-growth-supplements.jpg'),
(20, 'SOY PROTEIN (PROTEÍNA ISOLADA DE SOJA) 1KG - GROWT', 'A proteína de soja (Soy Protein) da Growth Supplements é um suplemento proteico perfeito para os vegetarianos que têm a hipertrofia como objetivo ou que apenas querem manter uma boa quantidade de proteínas no organismo para um cotidiano mais saudável.\r\nCom um altíssimo valor biológico, a proteína de soja oferece a quantidade ideal de nutrientes e proteínas para você enfrentar as suas atividades do dia a dia e também os treinos mais intensos. Inclusive, diferentemente do Whey, o Soy Protein pode ser consumido por pessoas intolerantes à lactose.', '118.80', 3, 'Vegano', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_soy-protein-prote-na-isolada-de-soja-1kg-growth-supplements.jpg'),
(21, 'SOY PROTEIN (PROTEÍNA ISOLADA DE SOJA) (1KG) (SABO', 'A soja é uma das melhores fontes de proteínas, vitaminas e compostos como isoflavonoides. Esse ingrediente é indispensável na rotina de qualquer pessoa, justamente por agregar tantos benefícios. Para quem está focado na saúde e deseja garantir um bom suplemento proteico, o Soy Protein é o produto certo. Um dos grandes diferenciais é que você consegue esse nutriente sem nenhum ingrediente animal. Por isso, o Soy Protein pode ser incluído em dietas veganas e vegetarianas sem qualquer preocupação. Se você está buscando por mais uma fonte de proteínas para uma dieta completa, vale a pena comprar agora a proteína de soja da Growth Supplements.', '39.60', 1, 'Vegano', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/162/product.png'),
(22, 'RICE PROTEIN (1KG) (SABOR CHOCOLATE) - GROWTH SUPP', 'O Rice Protein é um aliado ideal para os atletas veganos, vegetarianos ou com restrições a ingredientes de origem animal e que buscam a todo custo a hipertrofia. Muitos pensam que o arroz é capaz apenas de oferecer carboidratos - pelo contrário, ele pode fornecer proteínas e aminoácidos de grande importância para quem está focado na musculação. Com o Rice Protein Growth Supplements, você se torna capaz de superar qualquer obstáculo.', '126.00', 2, 'Vegano', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_rice-protein-1kg-growth-supplements.jpg'),
(23, 'RICE PROTEIN (SABOR NATURAL) (1KG) - GROWTH SUPPLE', 'Aliado aos treinos, o Rice Protein oferece a quantidade de proteína que você precisa para garantir a hipertrofia. Sejam ou não, todos conseguem aproveitar os seus benefícios ao incluir esse ingrediente na dieta, o que trará ainda mais resultados.Ao contrário do senso comum, o arroz não fornece apenas carboidratos. Sua estrutura pode também oferecer proteínas e aminoácidos essenciais para quem está focado na musculação.\r\n\r\nPrincipalmente no caso de veganos, que buscam uma alternativa às proteínas de origem animal como a proteína do leite ou a Proteína da Carne. Assim, você garante todos os nutrientes sem nenhum mistério e por um preço que cabe no seu bolso.', '63.00', 1, 'Vegano', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/159/product.png'),
(24, 'PROTEÍNA DA ERVILHA - (1KG) (COM SABOR) - GROWTH S', 'Engana-se quem pensa que somente é possível ingerir a quantidade ideal de proteínas para uma dieta por meio de suplementos de origem animal. A proteína da ervilha, ou Pea Protein, é um suplemento proteico de alto valor biológico e com nutrientes que garantem tudo aquilo que é preciso para potencializar os resultados de um treino bem intenso.\r\n\r\nA produção do Pea Protein tem a ervilha como base, ou seja, uma opção perfeita para veganos. Além da ervilha, são acrescentados diversos aminoácidos essenciais, ideais para quem tem a hipertrofia como objetivo principal.', '135.00', 2, 'Vegano', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_prote-na-da-ervilha-1kg-growth-supplements.jpg');

-- GABRIEL
INSERT INTO `produtos` (`id`, `nome`, `descricao`, `preco`, `quantidade`, `categoria`, `imagem`) VALUES
(25, 'WAXY MAIZE (1KG)', 'Quem pensa em aumentar a capacidade de treino e garantir ainda mais energia deve apostar no Waxy Maize. O produto foi desenvolvido pensando nas necessidades de praticantes de atividade física de alta intensidade, justamente porque ele fornece o combustível necessário para superar os limites e garantir resultados melhores. Trata-se de um produto feito à base de carboidratos complexos de alta qualidade, voltado especialmente para os atletas.\r\n\r\nQuem pensa que o carboidrato é um inimigo das dietas está muito enganado. Essas substâncias são importantíssimas, especialmente para quem pratica exercícios físicos. É um erro sempre pintar os carboidratos como vilões. Isso porque eles são fundamentais para o fornecimento de energia durante atividades físicas de todo tipo.\r\n\r\n', '21.60', 1, 'Carboidratos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/179/product.png'),
(26, 'DEXTROSE (1KG)', 'Um dos suplementos mais famosos para quem já pratica a academia, a Dextrose é bastante usada por quem busca os melhores resultados na musculação, tanto no caso de exercícios focados em hipertrofia quanto nos aeróbicos. Isso porque ela auxilia diretamente no desempenho, garantindo que você tenha mais energia para treinar. Você consegue executar exercícios cada vez mais intensos, por um período mais longo de tempo.\r\n\r\nOs benefícios são justamente para quem busca superar os limites — afinal, ganhar massa muscular depende também da quantidade e intensidade das séries nos exercícios que você executa. O importante é sempre aliar a prática de exercícios com uma alimentação saudável.\r\n\r\n', '14.40', 1, 'Carboidratos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/74/produto.png'),
(28, 'VITAMINA C (120 CAPS)', 'As vitaminas são essenciais para diversas funções do nosso organismo. A vitamina C é uma das mais famosas e reconhecidas, porque está associada à prevenção de diversas doenças e à melhora do sistema imunológico.\r\nEstudos recentes apontam também para um efeito de alívio no estresse, melhora na pele e até mesmo prevenção de problemas oftalmológicos e derrames.\r\n', '10.80', 1, 'Vitaminas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/173/product.png'),
(29, 'VITAMINA D (75 CÁPSULAS)', 'A concentração de vitamina D é responsável, em primeiro lugar, por regular a presença de cálcio e fósforo no sangue. Além disso, ainda está envolvida na homeostase de vários outros processos celulares, entre eles a síntese de antibióticos naturais pelas células de defesa dos mamíferos, modulação da autoimunidade e síntese de interleucinas inflamatórias, controle da pressão arterial e, como participa da regulação dos processos de multiplicação e diferenciação celular, é atribuído também a ela papel antioncogênico.', '13.50', 1, 'Vitaminas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/176/product.png'),
(30, 'VITAMINA E (75CAPS)', 'Vitamina E é um poderoso antioxidante dos lipídeos das membranas celulares, das proteínas e do DNA, que são as estruturas mais prejudicadas pela ação dos radicais livres. No caso dos idosos, ela também promove a função normal de células chamadas linfócitos T.\r\n\r\nEssas células, por sua vez, ajudam a defender o organismo de diversos microrganismos como vírus, fungos e alguns tipos de bactérias. Eles são produzidos na migração das células-mãe da medula óssea para o timo — é lá que esses linfócitos conseguem diferenciar os invasores das células e o próprio organismo.', '13.50', 1, 'Vitaminas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/178/produto.png'),
(31, 'COMPLEXO B 120 CAPS', 'O complexo B é um conjunto de vitaminas extremamente importante para diversas funções metabólicas do nosso corpo. Elas podem ser encontradas em alguns alimentos, e de maneira concentrada nos suplementos para suprir as quantidades que seu corpo necessita no dia a dia.\r\nO complexo B de vitaminas é composto por 8 destes micronutrientes, sendo eles: Vitamina B1 (ou Tiamina), B2 (ou Riboflavina), B3 (ou Niacina), B5 (ou Ácido Pantotênico), B6 (ou Piridoxina), B7 (ou Biotina), B9 (ou Ácido Fólico) e B12 (ou Cobalamina). Quanto mais nos exercitamos, maior é a demanda por esses nutrientes, e por isso, não deixe de incluí-los na sua rotina.\r\n\r\n', '19.80', 1, 'Vitaminas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/66/product.png'),
(32, 'MULTIVITAMÍNICO (120 CAPS) (NOVA FÓRMULA)', 'Fonte de nutrientes indispensáveis para uma rotina saudável, o multivitamínico não pode sair da sua mochila de treino. Com uma cápsula por dia, você garante a dose perfeita de uma série de vitaminas e minerais importantes para as mais diversas funções do seu organismo. Os benefícios aumentam ainda mais com a prática de atividades físicas, garantindo que você tenha sempre em mãos os melhores nutrientes para a recuperação pós-treino e a disposição de malhar cada vez melhor. São 120 cápsulas para garantir a força e a superação de qualquer desafio. Vai encarar?', '29.70', 1, 'Vitaminas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/107/produto.png'),
(33, 'L-CARNITINA (200GR)', 'A L-carnitina está envolvida no transporte de ácidos graxos até as mitocôndrias — compartimento celular onde os ácidos graxos são \"queimados\". Por meio da alimentação, é possível extrair essa substância de alimentos como carnes e produtos animais, principalmente. O abacate e a soja, por sua vez, podem atuar como fontes vegetais, mas a melhor fonte é a carne.\r\nA L Carnitina beneficia especialmente quem está buscando mais saúde, de forma geral. A tendência da academia, da musculação e do fitness como um todo tem se popularizado, despertando ainda mais o interesse sobre a L-carnitina.', '54.00', 1, 'Vitaminas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/83/produto.png'),
(34, '100% BATATA DOCE EM PÓ (SABOR NATURAL) (1KG)', 'A batata doce é um dos principais itens na lista de alimentos mais indicados para comer antes ou depois dos treinos. A fama faz com que os praticantes de atividades físicas busquem cada vez mais consumi-la, aproveitando os inúmeros benefícios da batata doce.\r\n\r\nNa vida dos atletas, a alimentação desempenha um papel central na busca pelos resultados. É por isso que esse ingrediente se torna muito importante em uma dieta, especialmente se o foco é o ganho de massa muscular.', '39.60', 10, 'Carboidratos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/1/product.png'),
(35, '(TOP) HIPERCALÓRICO (SABOR CHOCOLATE) (1KG)', 'O produto da Growth Supplements está entre os melhores hipercalóricos do mercado, e contém as seguintes quantidades em sua fórmula: 60% de Maltodextrina, 10% de Whey protein concentrado , 10% de Whey protein isolado, 10% de albumina, 5% de caseína micellar e 5% de proteína isolada de soja. É enviado um scoop que comporta 15g deste produto como brinde, caso disponível em estoque.\r\n\r\nO impacto no ganho de massa muscular é nítido graças à alta tecnologia aplicada na fabricação. Esse processo quebra as moléculas do Whey em partículas menores, permitindo que elas sejam absorvidas e disponibilizadas na circulação sanguínea em pouquíssimo tempo.', '40.50', 50, 'Carboidratos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/82/product.png'),
(36, 'ÓLEO DE PEIXE ULTRA (75 SOFTGEL)', 'O grande diferencial desse ingrediente é a presença do famoso Ômega 3 . Esse nutriente está presente em alta quantidade no óleo de peixe, especialmente se retirado de animais de águas profundas. Ele tem sido usado nos mais diferentes tipos de treino justamente por sua ação na recuperação muscular.\r\n\r\nA lista dos benefícios do óleo de peixe inclui a melhora nas lesões, garantindo que você consiga treinar por muito mais tempo. Isso porque o ômega 3 é composto de ácidos graxos que combatem os radicais livres, prejudiciais para quem deseja ganhar massa muscular.', '40.50', 10, 'Vitaminas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/112/product.png'),
(37, 'VITAMINA E ULTRA (1490UI) 120 CAPS', '* Não contém quantidades significativas de valor energéticos, carboidratos, proteínas, gorduras totais, gorduras saturadas, gorduras trans e sódio. % Valores diários recomendados com base em uma dieta de 2.000 Kcal ou 8400 KJ. Seus valores diários podem ser maiores ou menores dependendo de suas necessidades energéticas.', '54.00', 50, 'Vitaminas', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_vitamina-e-ultra-1490ui-120-caps-growth-supplements.jpg'),
(38, 'ANTI-OX 120 CAPS ', 'Alguns nutrientes podem impactar diretamente na sua recuperação. E,como todo bom atleta sabe, esse é um dos momentos mais importantes para a hipertrofia ? tanto para garantir que você tenha a disposição de treinar mais quanto para assegurar que construa melhor os músculos e consiga o tão sonhado aumento de massa muscular. O antioxidante é o melhor amigo do pós-treino. A Growth Supplements entende de todos os aspectos de uma rotina saudável e preparou um produto especial para nossos atletas. O Anti-OX possui nutrientes selecionados para melhorarcada aspecto da sua recuperação depois dos exercícios. Sua rotina não será a mesma com a ajuda desse produto revolucionário. Não fique de fora dessa inovação!', '18.00', 50, 'Vitaminas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/10/product.png'),
(39, 'ÓLEO DE PEIXE - ÔMEGA 3 (75 SOFTGEL)', 'Nem toda gordura é ruim. Muito pelo contrário, nosso corpo precisa de muitas delas para manter uma rotina saudável. Tudo, é claro, tendo consciência das quantidades e do tipo de gordura que consumimos. O ômega 3 é uma das principais, necessária para diversas funções metabólicas e encontrada frequentemente em peixes, sobretudo os de mares profundos e gelados. As gorduras são importantes também para a absorção das vitaminas lipossolúveis.\r\n\r\nPara garantir uma boa quantidade no seu dia a dia, nada melhor do que contar com produtos com qualidade Growth Supplements. Nosso complemento de ômega 3 possui 75 cápsulas - assim, fica mais fácil assegurar que todos os nutrientes tragam um impacto positivo na rotina.', '22.50', 20, 'Vitaminas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/111/product.png'),
(40, 'SPIRULINA (75 CÁPSULAS)', 'A Spirulina é um produto a base de cianobactéria, que tem ação funcional e diminui os níveis de colesterol no sangue. Ela atua no corpo e gera uma série de avanços nas funções metabólicas, além de proteger o organismo de doenças e infecções diversas.\r\n\r\nPor conta disso, a Spirulina tem se tornado cada vez mais famosa entre atletas e pessoas que buscam uma vida mais saudável. Ela possui uma série de elementos na sua fórmula natural, que foram passadas para o suplemento, sendo, inclusive, consumida por astronautas, quando estão em viagem pelo espaço.\r\n\r\nO alto índice de proteína, por exemplo, é ideal para manter o organismo forte e saudável. Isso tem feito com que as pessoas se interessem cada vez mais pelo uso desse suplemento, que virou um sucesso em todo o território nacional.', '27.00', 30, 'Vitaminas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/164/produto.png'),
(41, 'ÓLEO DE SEMENTE DE UVA (75CAPS) ', 'Os melhores ingredientes para uma boa rotina de treino podem estar presentes até mesmo nas coisas mais simples. É o caso do óleo de semente da uva, que contém uma série de nutrientes que impactam diretamente sobre seu treino e sua saúde. Até mesmo quem não treina sentirá o impacto positivo desse ingrediente na rotina. Ele é um excelente anti-inflamatório e pode ser útil para prevenir trombose, reduzir o colesterol e atuar na dilatação dos vasos sanguíneos. Na Growth Supplements você encontra o produto em 75 cápsulas concentradas com a quantidade que você precisa para uma rotina ainda mais saudável. Tudo isso com a segurança de um produto aprovado pelos testes mais rigorosos da Anvisa e com matéria-prima de primeira.', '19.80', 20, 'Vitaminas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/113/product.png'),
(42, 'POWER ARGININE (120CAPS)', 'Com a Arginina você garante resultados ainda melhores para as sessões de treino. Ela é um aminoácido que contribui muito para a obtenção de melhores resultados, especialmente para quem está focado na hipertrofia.\r\n\r\nCombinada sempre com uma dieta de ingestão de proteínas e carboidratos, a arginina garante impactos positivos cada vez maiores na rotina de exercícios. Além de auxiliar no processo de recuperação muscular, ela também é usada na produção de óxido nítrico no corpo. O resultado é um aumento do calibre dos vasos sanguíneos, produzindo ainda mais resultados.', '27.00', 20, 'Aminoácidos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/121/produto.png'),
(43, 'Amino Powder 10', 'Amino Power é o suplemento de aminoácidos mais completo que você vai ver! Contando com os principais aminoácidos, o Amino power é perfeito para completar a dieta de idosos que não conseguem comer carne, por exemplo, e crianças com restrição na alimentação, além de um praticante de atividade física. Muitas vezes, as dietas, por melhores que sejam, ainda precisam de complementos.\r\n\r\nPodendo ser diluído na água, o Amino Power é ideal para ser consumido em refeições que não possuam a quantidade ideal de proteína, que pode ser encontrada na carne, ovo, frango e peixe. Pode ser ingerida também durante o dia, cerca de 45 minutos antes dos treinos ou logo depois de praticar atividades físicas.', '70.00', 50, 'Aminoácidos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/1021/product.png'),
(44, 'TRIPTOFANO 120 CAPS - GROWTH SUPPLEMENTS', 'O mais novo suplemento de aminoácido da Growth trata-se de um aminoácido essencial ao nosso organismo. Após ser consumido, o triptofano pode ser convertido em serotonina, que por sua vez gera efeito de sensação de bem-estar de uma forma geral.\r\n\r\nJustamente por esse motivo que o triptofano é utilizado também como tratamento e prevenção da depressão - inclusive, pode facilitar muito o emagrecimento. Pode-se encontrar esse aminoácido em alguns alimentos como as nozes, por exemplo, ou em forma de suplemento alimentar.', '36.00', 60, 'Aminoácidos', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_triptofano-120-caps-growth-supplements.jpg'),
(45, 'POWER ALANINE (120 CAPS) - GROWTH SUPPLEMENTS', 'Os aminoácidos passam por algumas reações bioquímicas no organismo e, como resultado disso, são transformados em alanina. Após a transformação, esse aminoácido é transportado até o fígado, onde sofre mais reações bioquímicas e é levado aos tecidos musculares ativos para ser transformado em energia.\r\n\r\nO que vai determinar a necessidade do músculo por energia é a intensidade e duração do exercício. Isso significa que o ciclo deste aminoácido pelo organismo será definido pela sua rotina de treino.', '27.00', 40, 'Aminoácidos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/120/product.png'),
(46, 'L-LEUCINE (200GR) - GROWTH SUPPLEMENTS', 'Existem três aminoácidos essenciais na dieta humana, e ultimamente esses aminoácidos, principalmente a leucina, também conhecida como L leucina, tem ganhado muita atenção pelas suas propriedades e poder em estimular o desenvolvimento muscular. Conheça todos os benefícios da leucina e entenda por que esse produto faz uma grande diferença na busca pelo seu objetivo.', '39.60', 40, 'Aminoácidos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/86/product.png'),
(47, 'BCAA 120 COMPRIMIDOS TAB - GROWTH SUPPLEMENTS', 'Os aminoácidos são nutrientes indispensáveis na dieta de qualquer atleta. Para escolher os melhores, eleja os famosos aminoácidos essenciais como os primeiros da lista. A sigla nada mais é do que Aminoácidos de Cadeia Ramificada em inglês. Eles não são produzidos por nosso próprio corpo, este é o motivo pelo qual devemos inseri-los na dieta. Obtê-los através dos alimentos pode ser difícil, por isso a suplementação é justamente a solução ideal para muita gente, garantindo a quantidade de aminoácidos necessários em uma rotina de exercícios físicos. Ganhe mais força e evite a perda de massa muscular com a ajuda do BCAA Growth Supplements!', '45.90', 50, 'Aminoácidos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/25/product.png'),
(48, 'L-CARNITINA 120 CAPS - GROWTH SUPPLEMENTS', 'Um dos produtos que tem ganhado cada vez mais popularidade entre os praticantes de atividade física é a L-carnitina. Trata-se de um aminoácido produzido pelo organismo ou consumido via dieta — em alimentos ou na suplementação.\r\n\r\nEla está envolvida no transporte de ácidos graxos até as mitocôndrias — compartimento celular onde os ácidos graxos são \"queimados\". Por meio da alimentação, é possível extrair essa substância de alimentos como carnes e produtos animais, principalmente. O abacate e a soja, por sua vez, podem atuar como fontes vegetais, mas a melhor fonte é a carne.\r\n\r\nO produto da Growth Supplements garante a dose diária perfeita para não precisar se preocupar em incluir alimentos fonte deste aminoácido na dieta. Desse modo, fica mais fácil balancear a ingestão diária com a escolha de alimentos para uma rotina saudável. Bastante prático, não é mesmo?', '40.50', 40, 'Aminoácidos', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_l-carnitina-120-caps-growth-supplements.jpg'),
(49, 'L-CARNITINA (200GR)', 'Um dos produtos que tem ganhado cada vez mais popularidade entre os praticantes de atividade física é a L-carnitina. Trata-se de um aminoácido produzido pelo organismo ou consumido via dieta — em alimentos ou na suplementação.\r\n\r\nA L-carnitina está envolvida no transporte de ácidos graxos até as mitocôndrias — compartimento celular onde os ácidos graxos são \"queimados\". Por meio da alimentação, é possível extrair essa substância de alimentos como carnes e produtos animais, principalmente. O abacate e a soja, por sua vez, podem atuar como fontes vegetais, mas a melhor fonte é a carne.', '54.00', 35, 'Aminoácidos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/83/produto.png'),
(50, 'TAURINA 1000MG 120 COMPRIMIDOS - GROWTH SUPPLEMENT', 'A Taurina é um ácido orgânico que se encontra livre dentro da célula, detectado especialmente no coração, na retina, nos leucócitos, e no sistema nervoso central. Porém, em algumas situações o corpo não consegue produzir sozinho a quantidade necessária, já em outras situações pode ser interessante uma elevação na oferta deste nutriente. Um fato interessante é que, grande parte dos aminoácidos presentes no coração, condizem com a Taurina.', '54.00', 20, 'Aminoácidos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/1055/taurina.png'),
(51, 'CREATINA (100G) (CREAPURE®)', 'A creatina é um derivado de aminoácidos obtida através da dieta de síntese por nosso próprio organismo. Ela está presente essencialmente no músculo e auxilia na manutenção dos níveis de energia durante períodos breves de exercício intenso. Ou seja, sua função é crucial nos treinos com muito peso na busca pelo ganho de massa.', '23.40', 17, 'Aminoácidos', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_creatina-100g-creapure-growth-supplements.jpg'),
(52, 'CREATINA MONOHIDRATADA 100GR ', 'Quimicamente a Creatina Monohidratada é chamada de amina, é um composto derivado de aminoácidos que pode ser obtido através da dieta (alimentos), através de síntese feita por nosso próprio organismo ou através da suplementação. A creatina suplemento garante uma quantidade excelente desse nutriente no seu dia a dia. Isso faz com que o seu corpo tenha todas as necessidades supridas, com toda a energia para crescer e não perder a massa muscular conquistada nos treinos. A Creatina é produzida no nosso corpo nos rins, fígado e pâncreas, e secretada na corrente sanguínea até o tecido muscular. Sua fabricação é feita através de métodos avançados da tecnologia dos alimentos, uma de suas características é que seu sabor não é acentuado e por isso pode ser diluída no líquido de sua preferência.', '18.00', 30, 'Aminoácidos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/71/product.png'),
(53, 'CREATINA (250G) (CREAPURE®)', 'A creatina é um derivado de aminoácidos obtida através da dieta de síntese por nosso próprio organismo. Ela está presente essencialmente no músculo e auxilia na manutenção dos níveis de energia durante períodos breves de exercício intenso. Ou seja, sua função é crucial nos treinos com muito peso na busca pelo ganho de massa.', '41.40', 40, 'Aminoácidos', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/70/produto.png');

-- Eusebio
INSERT INTO `produtos` (`id`, `nome`, `descricao`, `preco`, `quantidade`, `categoria`, `imagem`) VALUES
(54, '(TOP) WHEY PROTEIN CONCENTRADO (1KG)', 'Whey Protein Growth é a proteína ideal para quem treina hipertrofia e quer ganhar massa muscular.\r\n\r\nIdeal porque é um suplemento de alto valor biológico, com grande concentração de proteínas e aminoácidos e também rico em Glutamina, BCAA e Leucina.', '76.50', 30, 'Proteínas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/185/01-desk.png'),
(55, '(TOP) WHEY PROTEIN ISOLADO (1KG)', 'Um produto com altíssima concentração de proteínas, o suplemento whey protein isolado é a melhor escolha para quem deseja garantir os melhores nutrientes para o desenvolvimento do corpo. Ele é produzido a partir do soro do leite, um subproduto resultante da porção aquosa do leite, gerada durante o processo de fabricação do queijo. Durante décadas, essa parte do leite era dispensada pela indústria de alimentos. Somente a partir da década de 70 os cientistas passaram a estudar suas propriedades.', '139.50', 50, 'Proteínas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/196/produto.png'),
(56, 'ALBUMINA 1KG - GROWTH SUPPLEMENTS', 'Um dos principais fatores que também garante a fama da albumina é justamente seu custo-benefício.\r\n\r\nOs bons resultados são alcançados e os gastos são relativamente baixos, especialmente ao se comparar com outros produtos usados para a mesma finalidade.\r\n\r\nÉ por isso que também se tornou um dos suplementos mais populares entre os praticantes de musculação e tem ganhado ainda mais destaque com o crescente número de pessoas que busca incluir essa forma de atividade física no dia a dia.', '59.40', 40, 'Proteínas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/6/produto.png'),
(57, '3 WHEY PROTEIN (1KG) - GROWTH SUPPLEMENTS', 'Se você estava em dúvida sobre em qual Whey Protein apostar, a solução está aqui. O 3 Whey Protein traz o equilíbrio perfeito entre o Whey Isolado, Concentrado e Hidrolisado. Cada um deles corresponde a uma fase da produção do famoso suplemento que está fazendo a cabeça de todos os atletas. O Concentrado da Growth possui 80% de proteínas e apresenta também carboidratos e gordura. Já o Whey Protein Isolado passa por uma filtragem ainda mais específica, chegando a 90% de concentração proteica. Por fim, a versão hidrolisada apresenta proteínas pré-digeridas com concentração de 90%. A mistura dos três, presente no 3 Whey Protein, garante todos esses benefícios em um só produto. São todos os nutrientes do Whey concentrados em uma opção perfeita para você!', '108.00', 10, 'Proteínas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/2/product.png'),
(58, 'CASEINATO DE CÁLCIO 1KG - GROWTH SUPPLEMENTS', 'Trata-se de uma das frações protéicas, uma das formas de proteínas presentes no leite. Isso mesmo, este suplemento é uma espécie de parente do whey protein, isso porque as proteínas do leite são divididas em duas famílias, as caseínas e as proteínas do soro (whey). Caseinato é obtido através da solubilização da caseína do leite e secagem através do processo de spray dryer. O fato é que esta é uma fonte de proteínas bastante especial porque é digerida lentamente. A diferença entre caseinato de cálcio e caseína é que o produto caseinato tem uma molécula de cálcio adicionada a estrutura da proteína caseína.', '76.50', 70, 'Proteínas', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_caseinato-de-c-lcio-1kg-growth-supplements-1.jpg'),
(59, '(TOP) WHEY E EGG (SABOR NATURAL) (1KG)', 'O whey protein concentrado é bem famoso entre os atletas. Ele é o produto mais querido entre os praticantes de musculação. Isso porque é responsável por facilitar o ganho de massa muscular e a redução de gordura corporal. Conheça os benefícios do whey:\r\nAumento da massa muscular;\r\nFortalece o sistema imunológico;\r\nPromove sensação de saciedade;\r\nAuxilia na redução de gorduras;\r\nÓtima fonte de proteínas de alto valor biológico;\r\nAlta concentração de aminoácidos essenciais e de cadeia ramificada;\r\nPotencializa a recuperação do tecido muscular;\r\nAjuda no combate aos radicais livres;\r\nCombate a inflamação da fibra muscular.', '72.00', 60, 'Proteínas', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_top-whey-e-egg-sabor-natural-1kg-growth-supplements.jpg'),
(60, 'SOY PROTEIN (PROTEÍNA ISOLADA DE SOJA) 1KG', 'Muitos que vivenciam o mundo atlético há tempos já devem ter ouvido falar que a soja é uma ótima fonte de proteína. A produção do Soy Protein tem justamente a soja como base, e o seu resultado traz esse alimento, só que de forma concentrada. Consumindo esse produto em momentos estratégicos do seu dia, potencializar os seus resultados fica ainda mais fácil. O Soy Protein é uma excelente fonte de proteína vegetariana.', '39.60', 39, 'Proteínas', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_soy-protein-prote-na-isolada-de-soja-1kg-growth-supplements.jpg'),
(61, 'SOY PROTEIN (PROTEÍNA ISOLADA DE SOJA) (1KG) (SABO', 'A soja é uma das melhores fontes de proteínas, vitaminas e compostos como isoflavonoides. Esse ingrediente é indispensável na rotina de qualquer pessoa, justamente por agregar tantos benefícios. Para quem está focado na saúde e deseja garantir um bom suplemento proteico, o Soy Protein é o produto certo. Um dos grandes diferenciais é que você consegue esse nutriente sem nenhum ingrediente animal. Por isso, o Soy Protein pode ser incluído em dietas veganas e vegetarianas sem qualquer preocupação. Se você está buscando por mais uma fonte de proteínas para uma dieta completa, vale a pena comprar agora a proteína de soja da Growth Supplements.', '39.60', 40, 'Proteínas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/162/product.png'),
(62, 'SIX PROTEIN (1KG) - GROWTH SUPPLEMENTS', 'Blend (mistura) é o nome dado a um produto que conta com várias fontes de energia. O Six Protein é o novo produto da Growth Supplements e conta com seis matrizes proteicas. Cada uma delas com tempo de digestão e absorção própria.\r\n\r\nA função do Six Protein é fornecer proteínas por várias horas em quantidades ideais a fim de que o organismo não transforme em gordura ou deixe de aproveitar o excesso de proteína ingerido. Do momento do consumo até cerca de seis horas, você estará abastecendo o seu corpo com proteínas e aminoácidos.', '136.00', 40, 'Proteínas', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_six-protein-1kg-growth-supplements.jpg'),
(63, 'RICE PROTEIN (SABOR NATURAL) (1KG)', 'Aliado aos treinos, o Rice Protein oferece a quantidade de proteína que você precisa para garantir a hipertrofia. Sejam ou não, todos conseguem aproveitar os seus benefícios ao incluir esse ingrediente na dieta, o que trará ainda mais resultados.Ao contrário do senso comum, o arroz não fornece apenas carboidratos. Sua estrutura pode também oferecer proteínas e aminoácidos essenciais para quem está focado na musculação.\r\n\r\nPrincipalmente no caso de veganos, que buscam uma alternativa às proteínas de origem animal como a proteína do leite ou a Proteína da Carne. Assim, você garante todos os nutrientes sem nenhum mistério e por um preço que cabe no seu bolso.', '63.00', 60, 'Proteínas', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/159/product.png'),
(64, 'RICE PROTEIN (1KG) (SABOR CHOCOLATE) ', 'Com certeza, sim! O Rice Protein nada mais é que um suplemento alimentar proteico com nutrientes retirados do arroz. A grande diferença dele para o Whey Protein é que o Rice Protein pode ser ingerido por pessoas que possuem alergias ou restrições a ingredientes de origem animal. Atletas veganos e vegetarianos podem aproveitar ao máximo todas as qualidades deste produto com tranquilidade.', '63.00', 20, 'Proteínas', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_rice-protein-1kg-growth-supplements.jpg'),
(65, 'PROTEÍNA DA ERVILHA - (1KG) (COM SABOR) ', 'Engana-se quem pensa que somente é possível ingerir a quantidade ideal de proteínas para uma dieta por meio de suplementos de origem animal. A proteína da ervilha, ou Pea Protein, é um suplemento proteico de alto valor biológico e com nutrientes que garantem tudo aquilo que é preciso para potencializar os resultados de um treino bem intenso.\r\n\r\nA produção do Pea Protein tem a ervilha como base, ou seja, uma opção perfeita para veganos. Além da ervilha, são acrescentados diversos aminoácidos essenciais, ideais para quem tem a hipertrofia como objetivo principal.\r\n\r\n', '67.50', 40, 'Proteínas', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_prote-na-da-ervilha-1kg-growth-supplements.jpg'),
(66, 'HOT TERMOGÊNICO - 60 caps', 'Metabolismo significa a quantidade de calorias necessárias para manutenção das atividades de um individuo. A quantidade de calorias usada pelo organismo é conhecida como taxa metabólica, ela pode variar de individuo para individuo de acordo com a pratica de atividade física, porte físico e também de acordo com uso de suplementos TERMOGÊNICOS, esta classe de suplementos é capaz de aumentar a temperatura corporal e por isso aumenta a necessidade de calorias. O novo produto da Growth Supplements trata-se de uma estratégia agressiva que pode ajudar quem esta buscando redução de peso, em especial redução de gorduras.', '65.00', 60, 'Termogênico', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/170/product.png'),
(67, 'CAFEÍNA (420MG) 120CAPS - GROWTH SUPPLEMENTS', 'A cafeína é um alcaloide pertencente ao grupo das drogas classificadas como metilxantinas (1,3,7- trimetilxantina). É uma substância lipossolúvel e sua ingestão oral é rapidamente absorvida pelo trato gastrointestinal³, podendo alcançar concentração máxima na corrente sanguínea entre 15 e 120 minutos após a sua ingestão.\r\n\r\nNo fígado, órgão responsável por metabolizar a cafeína, uma enzima denominada CYP1A2 promove a quebra da substância e a sua distribuição por todos os tecidos e órgãos, desencadeando diversos efeitos.\r\n\r\nUma das substâncias mais consumidas no mundo, a cafeína está em todo lugar. Desde o refrigerante até os chás e comprimidos para gripe. Sua ação tem despertado cada vez mais o interesse de quem se dedica aos treinos, especialmente por ser um excelente pré-treino e também um termogênico com ação efetiva no organismo.', '54.00', 50, 'Termogênico', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/38/produto.png'),
(68, 'CAFEÍNA (420MG) 60 CAPS - GROWTH SUPPLEMENTS (THER', 'A cafeína é um tipo de termogênico que proporciona muito mais vantagens para o organismo de um atleta e praticante de atividade física que quer melhorar o shape. Isso acontece porque o produto estimula o sistema nervoso e acelera algumas funções, a exemplo do metabolismo basal.\r\n\r\nA cafeína é um dos suplementos alimentares mais utilizados pelos atletas do #teamGrowth, já que produz adrenalina e deixa o corpo em estado de alerta. Saiba mais sobre esse produto que você encontra na Growth Supplements!', '31.50', 35, 'Termogênico', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_cafe-na-420mg-60-caps-growth-supplements-thermog-nico.jpg'),
(69, 'GENGIBRE EM PO 250GR - GROWTH SUPPLEMENTS', 'A planta tem origem asiática e pode ser usada, inclusive, em tratamentos médicos. O destaque dela é a raiz, que tem diversos nutrientes e um sabor marcante usado em várias receitas, especialmente na gastronomia tradicional de países orientais.\r\n\r\nVale a pena incluir esse saboroso e nutritivo item tanto para temperar quanto no preparo de chás e shakes no seu dia a dia. Aproveite todas as propriedades do gengibre em pó da Growth Supplements. São 250gr que conferem mais benefícios à sua rotina e que ajudam a conseguir resultados melhores com os treinos.', '21.60', 30, 'Termogênico', 'https://www.gsuplementos.com.br/upload/growth-layout-personalizado/produto/80/product.png'),
(70, 'PSYLLIUM, PIMENTA, GENGIBRE, CAFEÍNA E VITAMINAS 1', 'O produto Psyllium, Pimenta, Gengibre, Vitaminas e Cafeína trata-se de uma combinação altamente termogênica que pode ainda trazer maior disposição, aumento na saciedade e fornecer vitaminas. Cada ingrediente selecionado pela equipe de profissionais Growth Supplements possui uma função específica, porém, o maior dos benefícios é devido à ação sinérgica em conjunto de todos eles.\r\nBenefícios:\r\n\r\nPoderoso efeito termogênico de aumento da temperatura corporal que pode aumentar a queima de gorduras;\r\nFornece vitaminas intimamente ligadas ao metabolismo energético, ou seja, a forma como nosso organismo produz energia;\r\nNutrientes presentes na fórmula possuem efeito funcional, contribuindo para além do desempenho, podendo ajudar na manutenção do bom estado de saúde, como equilíbrio da flora intestinal.', '45.00', 40, 'Termogênico', 'https://www.gsuplementos.com.br/upload/produto/imagem/b_psyllium-pimenta-gengibre-cafe-na-e-vitaminas-120-caps-growth-supplements-1.jpg');
